// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enum.proto

#include "Enum.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace Protocol {
}  // namespace Protocol
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_Enum_2eproto[3];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_Enum_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_Enum_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_Enum_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nEnum.proto\022\010Protocol*F\n\017GameObjectStat"
  "e\022\010\n\004IDLE\020\000\022\010\n\004MOVE\020\001\022\n\n\006ATTACK\020\002\022\010\n\004DEA"
  "D\020\003\022\t\n\005SPAWN\020\004*\302\004\n\nObjectType\022\017\n\013OBJECT_"
  "NONE\020\000\022\n\n\006PLAYER\020\001\022\t\n\005ENEMY\020\002\022\n\n\006BULLET\020"
  "\003\022\013\n\007MINERAL\020\004\022\007\n\003GAS\020\005\022\t\n\005PROBE\020\006\022\n\n\006ZE"
  "ALOT\020\007\022\020\n\014DARKTEMPLLAR\020\010\022\013\n\007DRAGOON\020\t\022\n\n"
  "\006REAVER\020\n\022\013\n\007SHUTTLE\020\013\022\t\n\005SCOUT\020\014\022\013\n\007ARB"
  "ITER\020\r\022\n\n\006ARCHON\020\016\022\016\n\nDARKARCHON\020\017\022\014\n\010OB"
  "SERVER\020\020\022\013\n\007CARRIER\020\021\022\017\n\013INTERCEPTOR\020\022\022\013"
  "\n\007CORSAIR\020\023\022\017\n\013HIGHTEMPLAR\020\024\022\t\n\005NEXUS\020\025\022"
  "\t\n\005PYLON\020\026\022\017\n\013ASSIMILATOR\020\027\022\013\n\007GATEWAY\020\030"
  "\022\t\n\005FORGE\020\031\022\021\n\rPHOTON_CANNON\020\032\022\024\n\020CYBERN"
  "ETICS_CORE\020\033\022\022\n\016SHIELD_BATTERY\020\034\022\025\n\021ROBO"
  "TICS_FACILITY\020\035\022\014\n\010STARGATE\020\036\022\023\n\017CITADEL"
  "_OF_ADUN\020\037\022\030\n\024ROBOTICS_SUPPORT_BAY\020 \022\020\n\014"
  "FLEET_BEACON\020!\022\024\n\020TEMPLAR_ARCHIVES\020\"\022\017\n\013"
  "OBSERVATORY\020#\022\024\n\020ARBITER_TRIBUNAL\020$*K\n\016D"
  "isconnectCode\022\023\n\017DISCONNECT_NONE\020\000\022\010\n\004EX"
  "IT\020\001\022\016\n\nADMIN_EXIT\020\002\022\n\n\006RESIGN\020\003b\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_Enum_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Enum_2eproto = {
  false, false, 760, descriptor_table_protodef_Enum_2eproto, "Enum.proto", 
  &descriptor_table_Enum_2eproto_once, nullptr, 0, 0,
  schemas, file_default_instances, TableStruct_Enum_2eproto::offsets,
  nullptr, file_level_enum_descriptors_Enum_2eproto, file_level_service_descriptors_Enum_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_Enum_2eproto_getter() {
  return &descriptor_table_Enum_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_Enum_2eproto(&descriptor_table_Enum_2eproto);
namespace Protocol {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GameObjectState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[0];
}
bool GameObjectState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ObjectType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[1];
}
bool ObjectType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 27:
    case 28:
    case 29:
    case 30:
    case 31:
    case 32:
    case 33:
    case 34:
    case 35:
    case 36:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DisconnectCode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[2];
}
bool DisconnectCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
