// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCpGCg9HYW1lT2JqZWN0U3RhdGUSCAoE",
            "SURMRRAAEggKBE1PVkUQARIKCgZBVFRBQ0sQAhIICgRERUFEEAMSCQoFU1BB",
            "V04QBCrCBAoKT2JqZWN0VHlwZRIPCgtPQkpFQ1RfTk9ORRAAEgoKBlBMQVlF",
            "UhABEgkKBUVORU1ZEAISCgoGQlVMTEVUEAMSCwoHTUlORVJBTBAEEgcKA0dB",
            "UxAFEgkKBVBST0JFEAYSCgoGWkVBTE9UEAcSEAoMREFSS1RFTVBMTEFSEAgS",
            "CwoHRFJBR09PThAJEgoKBlJFQVZFUhAKEgsKB1NIVVRUTEUQCxIJCgVTQ09V",
            "VBAMEgsKB0FSQklURVIQDRIKCgZBUkNIT04QDhIOCgpEQVJLQVJDSE9OEA8S",
            "DAoIT0JTRVJWRVIQEBILCgdDQVJSSUVSEBESDwoLSU5URVJDRVBUT1IQEhIL",
            "CgdDT1JTQUlSEBMSDwoLSElHSFRFTVBMQVIQFBIJCgVORVhVUxAVEgkKBVBZ",
            "TE9OEBYSDwoLQVNTSU1JTEFUT1IQFxILCgdHQVRFV0FZEBgSCQoFRk9SR0UQ",
            "GRIRCg1QSE9UT05fQ0FOTk9OEBoSFAoQQ1lCRVJORVRJQ1NfQ09SRRAbEhIK",
            "DlNISUVMRF9CQVRURVJZEBwSFQoRUk9CT1RJQ1NfRkFDSUxJVFkQHRIMCghT",
            "VEFSR0FURRAeEhMKD0NJVEFERUxfT0ZfQURVThAfEhgKFFJPQk9USUNTX1NV",
            "UFBPUlRfQkFZECASEAoMRkxFRVRfQkVBQ09OECESFAoQVEVNUExBUl9BUkNI",
            "SVZFUxAiEg8KC09CU0VSVkFUT1JZECMSFAoQQVJCSVRFUl9UUklCVU5BTBAk",
            "KksKDkRpc2Nvbm5lY3RDb2RlEhMKD0RJU0NPTk5FQ1RfTk9ORRAAEggKBEVY",
            "SVQQARIOCgpBRE1JTl9FWElUEAISCgoGUkVTSUdOEANiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.GameObjectState), typeof(global::Protocol.ObjectType), typeof(global::Protocol.DisconnectCode), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum GameObjectState {
    [pbr::OriginalName("IDLE")] Idle = 0,
    [pbr::OriginalName("MOVE")] Move = 1,
    [pbr::OriginalName("ATTACK")] Attack = 2,
    [pbr::OriginalName("DEAD")] Dead = 3,
    [pbr::OriginalName("SPAWN")] Spawn = 4,
  }

  public enum ObjectType {
    [pbr::OriginalName("OBJECT_NONE")] ObjectNone = 0,
    [pbr::OriginalName("PLAYER")] Player = 1,
    [pbr::OriginalName("ENEMY")] Enemy = 2,
    [pbr::OriginalName("BULLET")] Bullet = 3,
    [pbr::OriginalName("MINERAL")] Mineral = 4,
    [pbr::OriginalName("GAS")] Gas = 5,
    [pbr::OriginalName("PROBE")] Probe = 6,
    [pbr::OriginalName("ZEALOT")] Zealot = 7,
    [pbr::OriginalName("DARKTEMPLLAR")] Darktempllar = 8,
    [pbr::OriginalName("DRAGOON")] Dragoon = 9,
    [pbr::OriginalName("REAVER")] Reaver = 10,
    [pbr::OriginalName("SHUTTLE")] Shuttle = 11,
    [pbr::OriginalName("SCOUT")] Scout = 12,
    [pbr::OriginalName("ARBITER")] Arbiter = 13,
    [pbr::OriginalName("ARCHON")] Archon = 14,
    [pbr::OriginalName("DARKARCHON")] Darkarchon = 15,
    [pbr::OriginalName("OBSERVER")] Observer = 16,
    [pbr::OriginalName("CARRIER")] Carrier = 17,
    [pbr::OriginalName("INTERCEPTOR")] Interceptor = 18,
    [pbr::OriginalName("CORSAIR")] Corsair = 19,
    [pbr::OriginalName("HIGHTEMPLAR")] Hightemplar = 20,
    [pbr::OriginalName("NEXUS")] Nexus = 21,
    [pbr::OriginalName("PYLON")] Pylon = 22,
    [pbr::OriginalName("ASSIMILATOR")] Assimilator = 23,
    [pbr::OriginalName("GATEWAY")] Gateway = 24,
    [pbr::OriginalName("FORGE")] Forge = 25,
    [pbr::OriginalName("PHOTON_CANNON")] PhotonCannon = 26,
    [pbr::OriginalName("CYBERNETICS_CORE")] CyberneticsCore = 27,
    [pbr::OriginalName("SHIELD_BATTERY")] ShieldBattery = 28,
    [pbr::OriginalName("ROBOTICS_FACILITY")] RoboticsFacility = 29,
    [pbr::OriginalName("STARGATE")] Stargate = 30,
    [pbr::OriginalName("CITADEL_OF_ADUN")] CitadelOfAdun = 31,
    [pbr::OriginalName("ROBOTICS_SUPPORT_BAY")] RoboticsSupportBay = 32,
    [pbr::OriginalName("FLEET_BEACON")] FleetBeacon = 33,
    [pbr::OriginalName("TEMPLAR_ARCHIVES")] TemplarArchives = 34,
    [pbr::OriginalName("OBSERVATORY")] Observatory = 35,
    [pbr::OriginalName("ARBITER_TRIBUNAL")] ArbiterTribunal = 36,
  }

  public enum DisconnectCode {
    [pbr::OriginalName("DISCONNECT_NONE")] DisconnectNone = 0,
    [pbr::OriginalName("EXIT")] Exit = 1,
    [pbr::OriginalName("ADMIN_EXIT")] AdminExit = 2,
    [pbr::OriginalName("RESIGN")] Resign = 3,
  }

  #endregion

}

#endregion Designer generated code
